title: Tova Perlman # your name (or website title) here
logo: "/images/TovaPerlmanProfPic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  ##Master's Degree in Urban Spatial Analytics
  <br></br>
  ###Interests in Data Visualization and Analytics centered around Housing and Urban Policy
  
  <br></br>
  <br></br>
  <a href="https://www.linkedin.com/in/tova-perlman-64a6a7155/">View My LinkedIn Profile</a> 
    <br></br>
    
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
